export const AppConstants = {
	MAX_COINS : 5
}

export const APPLICATION_CONSTANTS = {
	HOME_PAGE_URL : '/',
	DASHBOARD_URL: '/dashboard'
}

export const LOGIN_CONSTANTS = {
	LOGIN_INPUT_PLACE_HOLDER: "Enter your Login Address",
	LOGIN_BUTTON_TEXT : 'Login',
	INVALID_EMAIL_ERROR : 'Invalid Address'
}

export const DASHBOARD_CONSTANTS = {
	SEND_WIDGET_HEADING: "Send Money",
	AMOUNT_HEADING : 'Enter Amount',
	ADDRESS_HEADING: 'Enter Address',
	LOW_BALANCE_ERROR_MSG: 'Balance is low',
	SEND_BUTTON_TEXT: 'SEND',
	TRANSACTION_CHART_HEADING: 'Send and Receive Transactions',
	BALANCE_CHART_HEADING: 'Balance After Each Transaction'
}

export const ACTION_CONSTANTS = {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	SET_ADDRESS_DETAILS: 'SET_ADDRESS_DETAILS',
	SET_TRANSACTION_ERROR : 'SET_TRANSACTION_ERROR',
	SET_TRANSACTION_SUCCESS : 'SET_TRANSACTION_SUCCESS'
}